// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3QVsg_6Wu-LYbTGXEXdPBf-C9f2KsXDk',
    appId: '1:401726564613:web:a27ffcf6659275f0b62f6c',
    messagingSenderId: '401726564613',
    projectId: 'trash-collector-d35e6',
    authDomain: 'trash-collector-d35e6.firebaseapp.com',
    storageBucket: 'trash-collector-d35e6.appspot.com',
    measurementId: 'G-R4C74FWBZ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnVuwGLRI2kJI2lexsb_NTMYtaZvUiggU',
    appId: '1:401726564613:android:41c23e3a47d92f07b62f6c',
    messagingSenderId: '401726564613',
    projectId: 'trash-collector-d35e6',
    storageBucket: 'trash-collector-d35e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzRCNgHz55H0PoYv8pausskeFhb04adNI',
    appId: '1:401726564613:ios:ee063405ddd89d3cb62f6c',
    messagingSenderId: '401726564613',
    projectId: 'trash-collector-d35e6',
    storageBucket: 'trash-collector-d35e6.appspot.com',
    iosBundleId: 'com.example.trashCollectorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzRCNgHz55H0PoYv8pausskeFhb04adNI',
    appId: '1:401726564613:ios:d9b38cde90635ee1b62f6c',
    messagingSenderId: '401726564613',
    projectId: 'trash-collector-d35e6',
    storageBucket: 'trash-collector-d35e6.appspot.com',
    iosBundleId: 'com.example.trashCollectorApp.RunnerTests',
  );
}
